repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: clang-format
        name: clang-format
        entry: pwsh
        language: system
        files: ^(src|examples|test)/.*\.(c|cc|cpp|cxx|h|hpp|hh|ino)$
        args:
          - -NoLogo
          - -NoProfile
          - -ExecutionPolicy
          - Bypass
          - -File
          - tools/run-clang-format.ps1
      - id: cppcheck
        name: cppcheck
        entry: pwsh
        language: system
        files: ^(src|examples|test)/.*\.(c|cc|cpp|cxx|h|hpp|hh)$
        pass_filenames: false
        args:
          - -NoLogo
          - -NoProfile
          - -ExecutionPolicy
          - Bypass
          - -File
          - tools/run-cppcheck.ps1
