; PlatformIO Project Configuration File
;
; https://docs.platformio.org/page/projectconf.html

[platformio]
description = ESP32 C++17 BACnet/IP stack library with client and server support

[env:usb]
platform = espressif32
board = nodemcu-32s
framework = arduino
upload_port = COM3
monitor_speed = 115200

build_unflags =
	-std=gnu++11

build_flags =
	-Wno-deprecated-declarations
	-std=gnu++17

test_build_src = yes