// SPDX-License-Identifier: GPL-2.0-or-later WITH GCC-exception-2.0
#include "WindowsInterfaceSelection.h"
#include <winsock2.h>
#include <iphlpapi.h>
#include <ws2tcpip.h>
#include <cstdlib>
#include <cstring>
#include <cstdio>

BacnetIpEndpoint windowsBroadcastAddress(BacnetIpEndpoint address, BacnetIpEndpoint netmask) { BacnetIpEndpoint result; for (size_t i=0;i<4;++i) result.address[i]=static_cast<uint8_t>(address.address[i]|static_cast<uint8_t>(~netmask.address[i])); return result; }
WindowsInterfaceSelectionStatus windowsSelectInterface(const WindowsIpv4Interface* interfaces,size_t count,const BacnetIpEndpoint* requested,WindowsIpv4Interface& selected){ size_t matches=0; for(size_t i=0;i<count;++i){if(requested!=nullptr && std::memcmp(interfaces[i].address.address,requested->address,4)!=0) continue; selected=interfaces[i]; ++matches;} if(matches==1)return WindowsInterfaceSelectionStatus::Selected; return matches==0?(requested?WindowsInterfaceSelectionStatus::NotFound:WindowsInterfaceSelectionStatus::None):WindowsInterfaceSelectionStatus::Multiple; }
WindowsInterfaceSelectionStatus windowsDiscoverIpv4Interface(const BacnetIpEndpoint* requested,WindowsIpv4Interface& selected,WindowsIpv4Interface* candidates,size_t capacity,size_t& candidateCount){ candidateCount=0; ULONG size=0; if(GetAdaptersAddresses(AF_INET,GAA_FLAG_SKIP_ANYCAST|GAA_FLAG_SKIP_MULTICAST|GAA_FLAG_SKIP_DNS_SERVER,nullptr,nullptr,&size)!=ERROR_BUFFER_OVERFLOW)return WindowsInterfaceSelectionStatus::None; auto* data=static_cast<IP_ADAPTER_ADDRESSES*>(std::malloc(size)); if(data==nullptr)return WindowsInterfaceSelectionStatus::None; const ULONG result=GetAdaptersAddresses(AF_INET,GAA_FLAG_SKIP_ANYCAST|GAA_FLAG_SKIP_MULTICAST|GAA_FLAG_SKIP_DNS_SERVER,nullptr,data,&size); if(result==NO_ERROR) for(auto* adapter=data;adapter!=nullptr;adapter=adapter->Next){ if(adapter->OperStatus!=IfOperStatusUp||adapter->IfType==IF_TYPE_SOFTWARE_LOOPBACK)continue; for(auto* unicast=adapter->FirstUnicastAddress;unicast!=nullptr;unicast=unicast->Next){ auto* address=reinterpret_cast<sockaddr_in*>(unicast->Address.lpSockaddr); if(address==nullptr||address->sin_family!=AF_INET)continue; const uint32_t ip=ntohl(address->sin_addr.S_un.S_addr); if((ip&0xffff0000UL)==0xa9fe0000UL)continue; if(candidateCount<capacity){ auto& item=candidates[candidateCount]; std::snprintf(item.name,sizeof(item.name),"%s",adapter->AdapterName); for(size_t i=0;i<4;++i){item.address.address[i]=static_cast<uint8_t>(ip>>(24-i*8)); item.netmask.address[i]=static_cast<uint8_t>(i<unicast->OnLinkPrefixLength/8?255:0);} const uint8_t rem=static_cast<uint8_t>(unicast->OnLinkPrefixLength%8); if(rem!=0&&unicast->OnLinkPrefixLength/8<4)item.netmask.address[unicast->OnLinkPrefixLength/8]=static_cast<uint8_t>(0xff<<(8-rem)); ++candidateCount; } }} std::free(data); return windowsSelectInterface(candidates,candidateCount,requested,selected); }
