; PlatformIO Project Configuration File
;
; https://docs.platformio.org/page/projectconf.html

[platformio]
description = ESP32 BACnet/IP client demo with ConfigManager web UI

[env:usb]
platform = espressif32
board = nodemcu-32s
framework = arduino
upload_port = COM3
monitor_speed = 115200

build_unflags =
	-std=gnu++11

build_flags =
	-Wno-deprecated-declarations
	-std=gnu++17
	-DCM_ENABLE_LOGGING=0
	-DCM_ENABLE_VERBOSE_LOGGING=0
	-DCM_LOGGING_LEVEL=CM_LOG_LEVEL_WARN

test_build_src = yes

lib_extra_dirs =
	../..

lib_deps =
	vitaly.ruhl/ESP32 Configuration Manager@^4.2.2