; PlatformIO Project Configuration File
;
; https://docs.platformio.org/page/projectconf.html

[platformio]
description = ESP32 BACnet/IP client demo
; Keep build artifacts out of the library repository.
build_dir = ${sysenv.HOME}/.pio/esp32-bacnet-stack/examples/client-demo
libdeps_dir = ${sysenv.HOME}/.pio/esp32-bacnet-stack/examples/client-demo/libdeps

[env:usb]
platform = espressif32
board = nodemcu-32s
framework = arduino
monitor_speed = 115200
board_build.partitions = no_ota.csv

build_unflags =
	-std=gnu++11

build_flags =
	-Wno-deprecated-declarations
	-std=gnu++17
	-Iinclude
	-DCM_ENABLE_LOGGING=0
	-DCM_ENABLE_VERBOSE_LOGGING=0
	-DCM_ENABLE_OTA=0
	-DCM_DISABLE_GUI_LOGGING
	-DESP_BACNET_PROPERTY_CACHE_SIZE=24
	-DBACNET_LOG_MAX_OUTPUTS=1

lib_deps =
	https://github.com/vitalyruhl/ConfigurationsManager.git
	bblanchon/ArduinoJson@~7.4.3
	esphome/ESPAsyncWebServer-esphome@~3.4.0
	esphome/AsyncTCP-esphome@2.1.4
	symlink://../..

[env:usb_ota]
platform = espressif32
board = nodemcu-32s
framework = arduino
monitor_speed = 115200
board_build.partitions = default.csv

build_unflags =
	-std=gnu++11

build_flags =
	-Wno-deprecated-declarations
	-std=gnu++17
	-Iinclude
	-DCM_ENABLE_LOGGING=0
	-DCM_ENABLE_VERBOSE_LOGGING=0
	-DCM_ENABLE_OTA=1
	-DCM_DISABLE_GUI_LOGGING
	-DESP_BACNET_PROPERTY_CACHE_SIZE=24
	-DBACNET_LOG_MAX_OUTPUTS=1

lib_deps =
	https://github.com/vitalyruhl/ConfigurationsManager.git
	bblanchon/ArduinoJson@~7.4.3
	esphome/ESPAsyncWebServer-esphome@~3.4.0
	esphome/AsyncTCP-esphome@2.1.4
	symlink://../..
