; Read-only physical I/O binding for the ESP32 BACnet/IP server.

[platformio]
description = ESP32 BACnet/IP read-only I/O server example
default_envs = wifi-com4
build_dir = ${sysenv.HOME}/.pio/esp32-bacnet-stack/examples/io-example
libdeps_dir = ${sysenv.HOME}/.pio/esp32-bacnet-stack/examples/io-example/libdeps

[env]
platform = espressif32
board = nodemcu-32s
framework = arduino
monitor_speed = 115200
build_unflags =
	-std=gnu++11
build_flags =
	-Wno-deprecated-declarations
	-std=gnu++17
	-DCM_ENABLE_LOGGING=0
	-DCM_ENABLE_VERBOSE_LOGGING=0
	-DCM_DISABLE_GUI_LOGGING
lib_deps =
	vitaly.ruhl/ESP32 Configuration Manager@4.4.1
	paulstoffregen/OneWire@2.3.8
	milesburton/DallasTemperature@3.11.0
	adafruit/Adafruit SSD1306@2.5.13
	symlink://../..

[env:wifi-com4]
board_build.partitions = no_ota.csv
upload_port = COM4
monitor_port = COM4
build_flags =
	${env.build_flags}
	-DCM_ENABLE_OTA=0
