; PlatformIO Project Configuration File
;
; Local-only WAGO BACnet/IP client acceptance HIL runner.

[platformio]
description = Local WAGO BACnet/IP client acceptance HIL runner

[env:usb]
platform = espressif32
board = nodemcu-32s
framework = arduino
monitor_speed = 115200

lib_deps =
  symlink://../..

build_unflags =
  -std=gnu++11

build_flags =
  -Wno-deprecated-declarations
  -std=gnu++17
