; ESP32 BACnet/IP BME280 server demo.

[platformio]
description = ESP32 BACnet/IP BME280 server demo
default_envs = usb
build_dir = ${sysenv.HOME}/.pio/esp32-bacnet-stack/examples/server-bme280-demo
libdeps_dir = ${sysenv.HOME}/.pio/esp32-bacnet-stack/examples/server-bme280-demo/libdeps

[env]
platform = espressif32
board = nodemcu-32s
framework = arduino
monitor_speed = 115200
build_unflags =
	-std=gnu++11
build_flags =
	-Wno-deprecated-declarations
	-std=gnu++17
	-DCM_ENABLE_LOGGING=0
	-DCM_ENABLE_VERBOSE_LOGGING=0
	-DCM_DISABLE_GUI_LOGGING
lib_deps =
	vitaly.ruhl/ESP32 Configuration Manager@4.4.1
	ks-tec/BME280_I2C@1.4.1+002
	symlink://../..

[env:usb]
board_build.partitions = no_ota.csv
build_flags =
	${env.build_flags}
	-DCM_ENABLE_OTA=0
