; ESP32 BACnet/IP BME280 server demo.

[platformio]
description = ESP32 BACnet/IP BME280 server demo
default_envs = usb
build_dir = ${sysenv.HOME}/.pio/esp32-bacnet-stack/examples/server-bme280-demo
libdeps_dir = ${sysenv.HOME}/.pio/esp32-bacnet-stack/examples/server-bme280-demo/libdeps

[env]
platform = espressif32
board = nodemcu-32s
framework = arduino
monitor_speed = 115200
lib_ldf_mode = deep
build_unflags =
	-std=gnu++11
build_flags =
	-Wno-deprecated-declarations
	-std=gnu++17
	-DCM_ENABLE_LOGGING=0
	-DCM_ENABLE_VERBOSE_LOGGING=0
	-DCM_DISABLE_GUI_LOGGING
lib_deps =
	; ConfigManager V4.4.0, pinned because no v4.4.0 tag exists yet.
	https://github.com/vitalyruhl/ConfigurationsManager.git#cf545d69dbe67ab590a616714117a139a8f80283
	Wire
	Ticker
	ks-tec/BME280_I2C@1.4.1+002
	bblanchon/ArduinoJson@~7.4.3
	esphome/ESPAsyncWebServer-esphome@~3.4.0
	esphome/AsyncTCP-esphome@2.1.4
	symlink://../..

[env:usb]
board_build.partitions = no_ota.csv
build_flags =
	${env.build_flags}
	-DCM_ENABLE_OTA=0
